### PR TITLE
Append a no-break space to repeated messages.

### LINKED ISSUE #11: Safari+VoiceOver don't announce identical, repeated, strings
For more details, see the WordPress trac ticket:
https://core.trac.wordpress.org/ticket/36853

Two possible options so far:

- in https://github.com/Yoast/my-yoast/pull/224 we're experimenting clearing the aria-live region 1 second before the new message gets injected. In that case it makes sense because the messages are already debounced by 1 second. That seems to work. Maybe experimenting with some shorter delay.
- force Safari+VoiceOver to think the string is always different, maybe adding/removing some invisible characters each time... hacky but worth testing

### PR DESCRIPTION
**Pull request by afercia**
Fixes Safari+VoiceOver bug with identical, repeated, messages, appending a no-break space `\u00A0` character to the message string when it's the same as the previous message.

I've tried also with other characters like line separator (`\u2028`) and zero width no-break space (`\uFEFF`) but the no-break one looks more "safe" to me. The normal space (`\u0020`) doesn't work.

How to test:
- using Safari10+VoiceOver, open the Knowledge base search in the Help Center
- search for something that doesn't exist
- VoiceOver should announce "No results found."
- press again the Search button
- VoiceOver doesn't announce any message
- switch to this branch
- yarn link `a11y-speak` on Yoast SEO
- build the Yoast SEO js
- repeat the search, VoiceOver should announce "No results found."
- press again the Search button 
- verify Voiceover announces "No results found." again
- press again the Search button at your leisure, each time the search returns the message "No results found." VoiceOver should announce it correctly

screen shot 2017-04-18 at 16 27 37

If this gets merged, the temporary fix implemented on My Yoast should be removed, see https://github.com/Yoast/my-yoast/pull/224/commits/54b44b691cc10984173724fa7ccc03cdd1628c6a

Fixes #11

### CODE REVIEW

**Comment by afercia** [comment]
This PR also adds a `word-wrap: normal;` CSS property on the live-region elements, just in case.

**Comment by moorscode** [comment]
CR + Acceptance done :+1:

**Comment by afercia** [comment]
For the records, I've tested this also on the WordPress `speak` implementation, seems the Chrome inspector is making the `\u00a0` visible as `&nbsp;` but that should be just a Chrome thing. Firefox and Safari show just a space, so I'm guessing the Chrome inspector is a bit wrong here.
screen shot 2017-04-18 at 20 11 44
screen shot 2017-04-18 at 20 13 44

**Comment by moorscode** [comment]
I would say Chrome is the one doing the right thing here, as this is a non-breaking space (nbsp) but that doesn't show in Safari/FireFox.

**Pull request merged**
