### PR TITLE
Create the ARIA live regions when the DOM is ready.

### LINKED ISSUE #4: Create the two live regions when the DOM is ready
See [this comment on the wordpress-seo repo](https://github.com/Yoast/wordpress-seo/pull/5067#issuecomment-232288439).

Long story short, the two divs need to be there when the DOM is ready, so screen readers are aware there are two "live regions" they have to monitor for changes.

### PR DESCRIPTION
**Pull request by afercia**
Fixes #4 

This PR adds a way to execute a function when the DOM is ready that doesn't depend on jQuery `.ready()`. It's just a first pass, there are many different ways to do it and can certainly be improved. I'm assuming we don't support IE8 or other exotic browsers. Should be tested thoroughly. Any feedback and improvements welcome!

### CODE REVIEW

**Comment by omarreiss** [comment]
@afercia agreed on not supporting ie8. Fix looks promising at first glance. We should decide if we want to add separate ARIA live regions for every instance of the module or if the different instances of the module can share their regions.

**Comment by omarreiss** [comment]
I've created #7 for the regions question.

**Comment by omarreiss** [comment]
@afercia works for me in Chrome 51. Is this something we could simply merge and improve gradually?

**Comment by afercia** [comment]
@omarreiss haven't tested it extensively. On the other hand maybe the best way to test it would be merging it :)

**Comment by omarreiss** [comment]
Ok, I'll at least have @boblinthorst and @terw-dan test it in all browsers.

**Comment by terw-dan** [comment]
Tested this in Windows 10 with Internet Explorer 11, Opera, Chrome, Firefox and Vivaldi. Works great.  In combination with NDVA.

**Comment by afercia** [comment]
I've just finished testing it in all browsers I can test with:
Win 10: latest Chrome, Firefox, Edge, and IE11
OS X: latest Chrome, Firefox, Safari
the live regions are correctly created for me.

Tested also with screen readers:
Win10: Firefox+NVDA, Firefox+JAWS, IE11+JAWS, and for what is worth Chrome+ChromeVox (a not so used combo, and for good reasons)
OS X: Safari+VoiceOver
and the aria live regions work correctly since the first search.

**Comment by afercia** [comment]
Side note: the jQuery implementation is a bit more complex of course, see:
https://github.com/jquery/jquery/blob/edf7a43681ca0ba517b155fd5d748921660dfcd2/src/core/ready.js

of interest could be the fallback to `load` and maybe how they remove the event listeners.

**Comment by boblinthorst** [comment]
Tested the speaking functionality with three different browsers. Safari, Chrome and firefox. 

With Safari and Chrome, it all worked. With Firefox however, it did not. 

I tested by using the help center knowledge base search to search for "keyword", and check whether the screenreader read the amount of search results. 

Admittedly, the screenreader and firefox didn't seem to work well together. I got a "busy" message often. (not related to this pull, just made me wonder whether I was using the screenreader right.

**Comment by afercia** [comment]
@boblinthorst 

> I got a "busy" message often.

With VoiceOver and Firefox right? Yeah, it happens all the time, and not just on the KB search. They're just not the best combination.

**Comment by omarreiss** [comment]
I am fine with this implementation. Seems to work fine on most environments. Seems firefox and voiceover is not a combination that will be used much for obvious reasons.

**Pull request merged**
